### ISSUE TITLE
Error occurs when Algolia search

### ISSUE THREAD

**Issue by kenzo-tanaka** [slidevjs/docs#87] opened 2022-07-31 12:36 UTC
**Describe the bug**
Algolia search does not seem to be working.

**To Reproduce**
1. Go to top page https://sli.dev/
2. Cmd+k 
3. Type something + Enter (redirect to https://sli.devundefined/ )
4. Always no hits, and some error in developer console.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Browser: Google Chrome
 - Slidev version: Latest

**Comment by twitwi** [comment] 2022-09-21 19:24
@antfu if you know the cause (I imagine it may have happened with other projects)

**Comment by antfu** [comment] 2022-09-22 02:28
I don't know why nor how to fix it. I didn't change anything, but basically, all my docs's Algolia is broken.

**Comment by twitwi** [comment] 2022-09-22 14:43
> I don't know why nor how to fix it. I didn't change anything, but basically all my docs's Algolia is broken. man_shrugging

I looked a little: the client is making requests to some `undefined-dsn.algolia.net` which is due to it not receiving an `appId` (from the algolia config object). I'm not sure if it should be specified as in
https://github.com/vuejs/vitepress/blob/288aa48b92bc1d4dd74d064148a3b03373cdf1c3/docs/.vitepress/config.ts#L41
or if it should be a github secret or something (probably not as the apiKey is not).

Also, probably not the root of the problem but just in case, it seems `language` has been replaced by `lang` as in https://github.com/vuejs/vitepress/pull/459/files
so there might need an update there
https://github.com/slidevjs/docs/blob/18216961c9b829103d7ee5bc6c426cb525c3d51c/.vitepress/config.js#L259

**Comment by twitwi** [comment] 2022-10-28 11:42
This seems to be fixed by recent commits, good.

**Closed by twitwi** 2022-10-28 11:42 UTC
